apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: React-Config-App
  annotations:
    github.com/project-slug: JeevaGovindarajan/React-Config-App
    backstage.io/techdocs-ref: dir:.
spec:
  targets:
    - https://github.com/blamdemo/bigbadwolf1337/blob/master/catalog-info.yaml
